# weyl-std rustfmt - The Law
#
# Rust formatting rules
# Compatible with: rustfmt 1.7+ (nightly for some options)

edition = "2024"
max_width = 100
tab_spaces = 2
newline_style = "Unix"

# Imports
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Comments
wrap_comments = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 80
normalize_comments = true
normalize_doc_attributes = true

# Functions
fn_params_layout = "Tall"
fn_single_line = false

# Structs/Enums
struct_lit_single_line = true
enum_discrim_align_threshold = 20

# Other
use_small_heuristics = "Default"
use_field_init_shorthand = true
use_try_shorthand = true
force_multiline_blocks = false
format_strings = false
hex_literal_case = "Lower"
