# weyl-std stylua - The Law
#
# Lua formatting rules
# Compatible with: stylua 0.20+

column_width = 100
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferDouble"
call_parentheses = "Always"
collapse_simple_statement = "Never"

[sort_requires]
enabled = true
